default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: geronimo_development

test:
  <<: *default
  database: geronimo_test

production:
  <<: *default
  database: geronimo_production
  username: geronimo
  password: <%= ENV['GERONIMO_DATABASE_PASSWORD'] %>